apiVersion: v1
kind: Service
metadata:
  name: sfc-identity
  namespace: sfc
  labels:
    app.kubernetes.io/name: sfc-identity
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: sfc
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: kubectl
  annotations:
    owner: "krivorukandrey@gmail.com"
    purpose: "Internal ClusterIP service for Identity component in SFC application"
spec:
  selector:
    app.kubernetes.io/name: sfc-identity
  type: ClusterIP
  ports:
    - name: sfc-identity-cluster-service-http-port
      protocol: TCP
      port: 7265
      targetPort: 7265
    - name: sfc-identity-cluster-service-https-port
      protocol: TCP
      port: 7266
      targetPort: 7266
    - name: sfc-identity-cluster-service-bff-https-port
      protocol: TCP
      port: 443
      targetPort: 7266
  internalTrafficPolicy: Cluster